name:                haskell-csv-json
version:             0.1.0.0
github:              "uebayasi/haskell-csv-json"
license:             BSD3
author:              "&quot;Masao Uebayashi&quot;"
maintainer:          "&quot;uebayasi@gmail.com&quot;"
copyright:           "&quot;Copyright: (c) 2017 Masao Uebayashi&quot;"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/uebayasi/haskell-csv-json#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- cassava
- containers
- megaparsec
- text
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  haskell-csv-json-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-csv-json

tests:
  haskell-csv-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-csv-json
